require('dotenv').config()

const CONFIG = {}

CONFIG.PORT = process.env.PORT || 3000
CONFIG.NODE_ENV = process.env.NODE_ENV
CONFIG.DB_URL = process.env.DB_URL || 'localhost'
CONFIG.DB_NAME = process.env.DB_NAME || 'aahaar'
CONFIG.DB_USERNAME = process.env.DB_USERNAME
CONFIG.DB_RS_NAME = process.env.DB_RS_NAME
CONFIG.DB_PASSWORD = process.env.DB_PASSWORD
CONFIG.BASE_URL = process.env.BASE_URL
CONFIG.MAX_IMAGE_UPLOAD_SIZE_MB = process.env.MAX_IMAGE_UPLOAD_SIZE_MB

CONFIG.FIREBASE_ACCOUNT_TYPE =
  process.env.FIREBASE_ACCOUNT_TYPE || 'service_account'
CONFIG.FIREBASE_PROJECT_ID = process.env.FIREBASE_PROJECT_ID
CONFIG.FIREBASE_PRIVATE_KEY_ID = process.env.FIREBASE_PRIVATE_KEY_ID
CONFIG.FIREBASE_PRIVATE_KEY = process.env.FIREBASE_PRIVATE_KEY.replace(
  /\\n/g,
  '\n'
)
CONFIG.FIREBASE_CLIENT_EMAIL = process.env.FIREBASE_CLIENT_EMAIL
CONFIG.FIREBASE_CLIENT_ID = process.env.FIREBASE_CLIENT_ID
CONFIG.FIREBASE_AUTH_URI = process.env.FIREBASE_AUTH_URI
CONFIG.FIREBASE_TOKEN_URI = process.env.FIREBASE_TOKEN_URI
CONFIG.FIREBASE_AUTH_PROVIDER_x509_CERT_URL =
  process.env.FIREBASE_AUTH_PROVIDER_x509_CERT_URL
CONFIG.FIREBASE_CLIENT_x509_CERT_URL = process.env.FIREBASE_CLIENT_x509_CERT_URL

CONFIG.AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID
CONFIG.AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY
CONFIG.AWS_S3_BUCKET_NAME = process.env.AWS_S3_BUCKET_NAME

module.exports = CONFIG
